apiVersion: v1
kind: Service
metadata:
  name: opendesign-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: opendesign
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      name: http
